vim.pack.add({ 'https://github.com/romus204/tree-sitter-manager.nvim.git' })
require('tree-sitter-manager').setup()
-- return {
-- 	{
-- 		"nvim-treesitter/nvim-treesitter",
-- 		lazy = false,
-- 		build = ":TSUpdate",
-- 		dependencies = {
-- 			"nvim-treesitter/nvim-treesitter-textobjects",
-- 			"nvim-treesitter/nvim-treesitter-context",
-- 		},
-- 	},
-- 	{
-- 		"nvim-treesitter/nvim-treesitter-textobjects",
--     branch = "main",
-- 		config = function()
-- 			require("nvim-treesitter-textobjects").setup({
-- 				select = {
-- 					lookahead = true,
-- 				},
-- 				move = {
-- 					set_jumps = true,
-- 				},
-- 			})
-- 		end,
-- 	},
-- }
